name: webHooks

on: 
  repository_dispatch:
    types: seo

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: |
        echo My name is P3TERX.
        echo Hello World!
        echo ${{ github.event.client_payload }}
