name: webHooks

# on: 
#   repository_dispatch:
#     types: seo
on:
  issues:
    types: [opened, edited, milestoned]


jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: |
        echo My name is P3TERX.
        echo Hello World!
        echo ${{ github.event.direction }}
        echo ${{ github.event }}
